// Tests for the app layer's pure logic.
//
// The macOS app is built by a direct `swiftc` invocation rather than SwiftPM
// (see app/macos/build_app.sh for why), so there is no XCTest bundle to hang
// tests on. This is the smallest thing that works: a plain executable that
// compiles the dependency-free Swift sources alongside these assertions and
// exits non-zero when one fails.
//
// The file must be called main.swift: top-level code is only allowed there.
//
// Only files that import nothing beyond Foundation can be tested this way, so
// keep pure logic in pure files. That constraint is a feature — it is what
// stopped export bitrate arithmetic living inside a Metal-importing file.

import Foundation

var failures = 0
var checks = 0

func check(_ ok: Bool, _ what: String) {
    checks += 1
    if !ok { failures += 1; print("  FAIL  \(what)") }
}

func near(_ a: Double, _ b: Double, _ tol: Double, _ what: String) {
    check(abs(a - b) <= tol, "\(what): \(a) is not within \(tol) of \(b)")
}

// ---------------------------------------------------------------- presets

print("ExportPreset")

check(!ExportPreset.all.isEmpty, "there are presets at all")
check(Set(ExportPreset.all.map(\.id)).count == ExportPreset.all.count,
      "preset ids are unique")

for p in ExportPreset.all {
    check(p.width % 2 == 0 && p.height % 2 == 0,
          "\(p.id) has even dimensions — H.264/HEVC require it")
    check(p.bitrateKbps > 0, "\(p.id) has a bitrate")
    // PRODUCT_DIRECTION §7: named by destination, never by resolution.
    check(!p.name.contains("1080") && !p.name.contains("720") && !p.name.contains("4K")
          || p.name.contains("YouTube"),
          "\(p.id) is named by resolution rather than destination: \(p.name)")
}

let email = ExportPreset.all.first { $0.targetMegabytes != nil }!
check(email.targetMegabytes == 25, "the size-targeted preset aims at 25 MB")

// A short clip cannot benefit from more bitrate than the preset allows, so the
// solver must not inflate quality past the ceiling.
check(email.bitrate(forSeconds: 10) == email.bitrateKbps,
      "a short clip should use the preset's own bitrate")
check(email.estimatedMegabytes(forSeconds: 10) < 25,
      "a 10 s export must be under the target")
check(email.sizeWarning(forSeconds: 10) == nil, "a short export needs no warning")

// A middling length must be SOLVED for, landing under the target.
for seconds in [60.0, 120.0, 240.0, 390.0] {
    let mb = email.estimatedMegabytes(forSeconds: seconds)
    check(mb <= 25, "a \(Int(seconds)) s export estimated \(mb) MB, over the 25 MB target")
    check(email.sizeWarning(forSeconds: seconds) == nil,
          "a \(Int(seconds)) s export should still fit")
}

// Past the point where the floor binds, the promise cannot be kept — and the
// preset must SAY so rather than quietly producing an oversized file.
let tooLong = 3600.0
check(email.bitrate(forSeconds: tooLong) == ExportPreset.floorKbps,
      "an hour-long export should hit the quality floor")
check(email.estimatedMegabytes(forSeconds: tooLong) > 25,
      "an hour at the floor cannot fit in 25 MB — the test premise")
check(email.sizeWarning(forSeconds: tooLong) != nil,
      "an export that cannot meet its size target must warn")

// The boundary itself: the warning must appear exactly when the estimate does
// not fit, with no window where it silently overshoots.
var lastFitting = 0.0
var firstWarning = 0.0
for s in stride(from: 10.0, through: 2000.0, by: 5.0) {
    let fits = email.estimatedMegabytes(forSeconds: s) <= 25
    let warned = email.sizeWarning(forSeconds: s) != nil
    check(fits != warned, "at \(s) s: fits=\(fits) but warned=\(warned)")
    if fits { lastFitting = s } else if firstWarning == 0 { firstWarning = s }
}
check(firstWarning > lastFitting, "the warning starts after the last fitting length")
print("  fits up to ~\(Int(lastFitting)) s; warns from ~\(Int(firstWarning)) s")

// Presets without a target are never warned about and never re-solved.
for p in ExportPreset.all where p.targetMegabytes == nil {
    check(p.bitrate(forSeconds: 9999) == p.bitrateKbps,
          "\(p.id) has no size target, so its bitrate must not change")
    check(p.sizeWarning(forSeconds: 9999) == nil, "\(p.id) should never warn")
}

// Nonsense durations must not produce nonsense bitrates.
for s in [0.0, -5.0, Double.nan] {
    let b = email.bitrate(forSeconds: s)
    check(b > 0, "duration \(s) produced bitrate \(b)")
}


// ---------------------------------------------------------------- cube LUTs

print("CubeLUT")

// A 2x2x2 identity cube, written the way a real file writes one.
let identity = """
# Generated by a tool
TITLE "Identity"
LUT_3D_SIZE 2
DOMAIN_MIN 0.0 0.0 0.0
DOMAIN_MAX 1.0 1.0 1.0

0.0 0.0 0.0
1.0 0.0 0.0
0.0 1.0 0.0
1.0 1.0 0.0
0.0 0.0 1.0
1.0 0.0 1.0
0.0 1.0 1.0
1.0 1.0 1.0
"""
do {
    let lut = try CubeLUT.parse(identity)
    check(lut.size == 2, "size is read")
    check(lut.rgb.count == 8, "all 8 entries are read, got \(lut.rgb.count)")
    check(lut.rgb[0] == SIMD3<Float>(0, 0, 0), "first entry")
    check(lut.rgb[7] == SIMD3<Float>(1, 1, 1), "last entry")
    check(lut.domainMax == SIMD3<Float>(1, 1, 1), "domain is read")
    check(lut.rgbaFloats().count == 32, "packs to RGBA")
    check(lut.rgbaFloats()[3] == 1, "alpha is 1")
} catch { check(false, "a valid identity LUT failed to parse: \(error)") }

// Real files vary: tabs, trailing comments, blank lines, odd key case.
let messy = """
\tlut_3d_size\t2

0.0 0.0 0.0   # black
1 0 0
0 1 0\t
1 1 0
0 0 1
1 0 1
0 1 1
1 1 1
"""
do {
    let lut = try CubeLUT.parse(messy)
    check(lut.size == 2, "lowercase keys, tabs and trailing comments are tolerated")
    check(lut.rgb.count == 8, "entries survive the mess")
} catch { check(false, "a messy but valid LUT failed to parse: \(error)") }

// Failures must be specific, because "that didn't work" is useless when a
// creator is trying to find out why their LUT will not load.
func failsToParse(_ text: String, _ what: String) {
    do { _ = try CubeLUT.parse(text); check(false, "\(what) should not have parsed") }
    catch { checks += 1 }
}
failsToParse("just some text\n", "a file with no LUT_3D_SIZE")
failsToParse("LUT_1D_SIZE 32\n0 0 0\n", "a 1D LUT")
failsToParse("LUT_3D_SIZE 2\n0 0 0\n1 0 0\n", "a truncated cube")
failsToParse("LUT_3D_SIZE 1\n0 0 0\n", "a size-1 cube")
failsToParse("LUT_3D_SIZE 500\n", "an absurd size")

// An incomplete cube reports both numbers, so the user can see how far off it is.
do {
    _ = try CubeLUT.parse("LUT_3D_SIZE 2\n0 0 0\n")
    check(false, "should have thrown")
} catch let e as CubeLUT.Failure {
    check(e.description.contains("8"), "the error names the expected count: \(e)")
} catch { check(false, "wrong error type") }

// ---------------------------------------------------------------- result

print(failures == 0
      ? "\n\(checks) checks passed"
      : "\n\(failures) of \(checks) checks FAILED")
exit(failures == 0 ? 0 : 1)
