#!/usr/bin/env python3
"""Build the acknowledgements file that ships inside the app.

Generated from the ARTEFACTS THAT ACTUALLY SHIP, never from a hand-kept list:

  * the dylibs in the bundle say which native libraries are present;
  * `cargo metadata` says which Rust crates are linked in;
  * the licence texts come from the build prefixes, which carry their own.

A hand-maintained NOTICE file is wrong the day after somebody adds a dependency,
and nobody notices because nothing checks it. This cannot drift: add a crate and
it appears here; remove a library and it goes.

Both licences we ship under require this file to exist.

  MIT  — the copyright notice and permission notice must accompany all copies.
  LGPL — §6 requires the licence text, prominent notice that the library is
         used, and that the user be able to relink with their own build.

Exits non-zero when something ships whose licence text cannot be found, because
shipping an unattributed dependency is the failure this exists to prevent.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def bundled_dylibs(app: Path) -> set[str]:
    """Native libraries actually inside the bundle, by base name."""
    fw = app / "Contents" / "Frameworks"
    names = set()
    for p in fw.glob("*.dylib"):
        names.add(re.sub(r"\.\d.*$", "", p.name).removesuffix(".dylib"))
    return names


def shipped_crates() -> list[tuple[str, str, str]]:
    """Third-party Rust crates in the normal dependency closure.

    Build-only and dev-only dependencies are excluded deliberately: cbindgen
    runs at build time and its code is not in anything we hand to a user, so
    attributing it would be padding rather than compliance.
    """
    try:
        out = subprocess.run(
            ["cargo", "metadata", "--format-version", "1",
             "--filter-platform", "aarch64-apple-darwin"],
            cwd=ROOT / "core", capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError):
        return []
    if out.returncode != 0:
        return []
    meta = json.loads(out.stdout)
    pkgs = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    roots = [p["id"] for p in meta["packages"] if p["name"].startswith("mediacore")]

    seen: set[str] = set()

    def walk(pid: str) -> None:
        if pid in seen:
            return
        seen.add(pid)
        for dep in nodes.get(pid, {}).get("deps", []):
            kinds = {k.get("kind") for k in dep.get("dep_kinds", [])}
            if None in kinds:          # None == a normal dependency
                walk(dep["pkg"])

    for r in roots:
        walk(r)

    crates = []
    for pid in seen:
        p = pkgs[pid]
        if p["name"].startswith("mediacore"):
            continue
        crates.append((p["name"], p["version"], p.get("license") or "(undeclared)"))
    return sorted(crates)


def crate_licence_text(name: str, version: str) -> str | None:
    """The crate's own licence file, from the vendored source cargo downloaded."""
    for src in (Path.home() / ".cargo" / "registry" / "src").glob("*"):
        d = src / f"{name}-{version}"
        if not d.is_dir():
            continue
        for candidate in ("LICENSE-MIT", "LICENSE-APACHE", "LICENSE",
                          "LICENSE.md", "LICENSE.txt", "COPYING"):
            text = read(d / candidate)
            if text:
                return text
    return None


def rule(title: str) -> str:
    return f"\n{'=' * 78}\n{title}\n{'=' * 78}\n"


def main() -> int:
    app = ROOT / "app" / "macos" / "Editor.app"
    ff = ROOT / "build" / "ffmpeg-lgpl" / "share" / "licences"
    wh = ROOT / "build" / "whisper" / "share" / "licences"
    vendored = ROOT / "third_party" / "licences"

    missing: list[str] = []
    out: list[str] = []

    out.append("ACKNOWLEDGEMENTS")
    out.append("")
    out.append("This application is built on open-source software. The licences below")
    out.append("are reproduced in full, as those licences require.")
    out.append("")
    out.append("Generated by tools/gather_licences.py from the components actually")
    out.append("present in this build — not from a maintained list.")

    ff_versions = read(ff / "VERSIONS.txt") or ""
    wh_versions = read(wh / "VERSIONS.txt") or ""
    dylibs = bundled_dylibs(app)

    # ---- FFmpeg -----------------------------------------------------------
    if any(d.startswith("libav") or d.startswith("libsw") for d in dylibs):
        text = read(ff / "FFmpeg-LGPL-2.1.txt")
        version = next((l for l in ff_versions.splitlines() if l.startswith("FFmpeg")), "FFmpeg")
        out.append(rule(version + " — GNU Lesser General Public License v2.1 or later"))
        out.append(
            "This application uses libraries from the FFmpeg project, which are\n"
            "licensed under the LGPL version 2.1 or later. FFmpeg is NOT part of\n"
            "this application; it is a separate work, used as a shared library.\n"
            "\n"
            "This build enables no GPL or non-free components. The exact configure\n"
            "flags are recorded in the build script that produced it, and a check\n"
            "in this project's CI reads the configuration string back out of the\n"
            "compiled libraries to confirm it.\n"
            "\n"
            "YOUR RIGHT TO MODIFY AND RELINK (LGPL section 6). The FFmpeg libraries\n"
            "ship as separate dynamic libraries inside this application bundle, in\n"
            "Contents/Frameworks. You may replace them with your own build of the\n"
            "same version, or a modified one, and the application will use it,\n"
            "provided the interfaces remain compatible.\n"
            "\n"
            "CORRESPONDING SOURCE. The unmodified source for the exact version above\n"
            "is available from https://ffmpeg.org/releases/ . The script used to\n"
            "configure and build it is third_party/ffmpeg/build.sh in this project's\n"
            "source repository, and it applies no patches to FFmpeg.\n")
        if text:
            out.append(text)
        else:
            missing.append("FFmpeg LGPL text")

    # ---- LAME -------------------------------------------------------------
    if "libmp3lame" in dylibs:
        text = read(ff / "LAME-LGPL-2.1.txt")
        version = next((l for l in ff_versions.splitlines() if l.startswith("LAME")), "LAME")
        out.append(rule(version + " — GNU Lesser General Public License v2.1 or later"))
        out.append(
            "MP3 encoding is provided by LAME, licensed under the LGPL version 2.1\n"
            "or later. It ships as a separate dynamic library in Contents/Frameworks\n"
            "and may be replaced as described above. Source for the exact version is\n"
            "available from https://lame.sourceforge.io/ .\n")
        if text:
            out.append(text)
        else:
            missing.append("LAME LGPL text")

    # ---- whisper.cpp ------------------------------------------------------
    model = app / "Contents" / "Resources" / "ggml-base-q5_1.bin"
    if model.exists():
        text = read(wh / "whisper.cpp-MIT.txt")
        out.append(rule((wh_versions.strip() or "whisper.cpp") + " — MIT License"))
        out.append(
            "Speech recognition is performed on this device by whisper.cpp, which\n"
            "also contains the ggml tensor library. No audio is transmitted\n"
            "anywhere: the application contains no network code in this path.\n")
        if text:
            out.append(text)
        else:
            missing.append("whisper.cpp MIT text")

        # ---- the model weights, which are a separate copyright ------------
        text = read(vendored / "whisper-model-openai.txt")
        out.append(rule("Whisper model weights — MIT License"))
        out.append(
            "The speech recognition model bundled with this application\n"
            "(ggml-base-q5_1.bin) is derived from OpenAI's Whisper, whose code AND\n"
            "MODEL WEIGHTS are released under the MIT licence. The bundled file is a\n"
            "quantised conversion of the published weights.\n")
        if text:
            out.append(text)
        else:
            missing.append("Whisper model MIT text")

    # ---- NVIDIA codec headers (Windows builds only) -----------------------
    #
    # Headers, not a library: nothing of NVIDIA's is redistributed and the
    # encoder is loaded from the user's driver. But the loader inlines code
    # into libavcodec, so the notice ships. Cheap, and errs the right way.
    nv = read(ff / "nv-codec-headers-MIT.txt")
    if nv:
        version = next((l for l in ff_versions.splitlines()
                        if l.startswith("nv-codec-headers")), "nv-codec-headers")
        out.append(rule(version + " — MIT License"))
        out.append(
            "NVIDIA's codec headers, used to build hardware video encoding and\n"
            "decoding support. No NVIDIA software is included in this\n"
            "application: the encoder lives in the graphics driver already\n"
            "installed on this machine and is loaded at runtime.\n")
        out.append(nv)

    # ---- Rust crates ------------------------------------------------------
    crates = shipped_crates()
    if crates:
        out.append(rule("Rust libraries"))
        out.append("Statically linked into this application:\n")
        for name, version, lic in crates:
            out.append(f"  {name} {version} — {lic}")
        out.append("")
        for name, version, lic in crates:
            text = crate_licence_text(name, version)
            out.append(rule(f"{name} {version} — {lic}"))
            if text:
                out.append(text)
            else:
                missing.append(f"{name} {version}")

    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "Acknowledgements.txt"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out), encoding="utf-8")

    kb = dest.stat().st_size / 1024
    print(f"  wrote {dest.relative_to(ROOT) if dest.is_relative_to(ROOT) else dest} "
          f"({kb:.0f} KB, {len(crates)} crates)")

    if missing:
        print("\nERROR: shipping components with no licence text:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
